### PR TITLE
Fixes character encoding inside of <center> + minor cleanup

### PR DESCRIPTION
**Pull request by josh18**
@kball might be interested in this as I just realised you were working on something similar.

### CODE REVIEW

**Comment by rafibomb** [comment]
Awesome @josh18 ! 
@kball does this work as a comprehensive solution to the character encoding you are working on?

**Comment by rafibomb** [comment]
@josh18 Looking to pull this in for v2.2 coming soon. Are you able to add a test case here so we can ensure it passes from here on out?

https://github.com/zurb/inky/blob/master/test/inky.js

**Comment by josh18** [comment]
Sure, I haven't really written tests before so might need some help / advice. Should I modify this test `doesn't decode entities if non default cheerio config is given` or create a separate test?

**Comment by rafibomb** [comment]
Good question - @kball How would you set this test up?

**Comment by rafibomb** [comment]
@josh18 I believe https://github.com/zurb/inky/pull/37 resolves this. We'll close this here, please submit again if you see more characters converted - thanks!

**Comment by josh18** [comment]
Thanks, do you know if "Removes [data-parsed] from final output" got added?

**Pull request closed without merging**
