### PR TITLE
Make default cheerio options not escape characters

### PR DESCRIPTION
**Pull request by kball**
Fixes the escaping issues we've been seeing.

### CODE REVIEW

**Comment by westonganger** [comment]
+1

**Comment by Twissi** [comment]
👍  great stuff

**Comment by dhigginbotham** [comment]
:100: This issue has caused me quite a great amount of silly explanations for our current work around. :+1:

**Comment by axelson** [comment]
What is the status on this? This is a show-stopper for us. It looks like the Milestone is 2.1.1, but the current release of Inky is 1.3.5?

**Comment by axelson** [comment]
Also I did some testing with this PR (actually with the fix-character-escaping branch) and it is better but it still doesn't support ERB syntax. e.g. `<%= event.name %>`, although perhaps that is out of scope of this PR.

**Comment by kball** [comment]
This turned out to be incomplete because by making cheerio be more stringent, we then resulted in errors with stuff embedded within that was invalid xml (like ERB, or <<template>> stuff).  So to work around that, I implemented a <raw> tag that just forces some stuff to not be parsed.  Going to resubmit this branch against develop.  To do this I needed to slightly rework how inky interacts with cheerio (moving the parsing internal to Inky rather than external) so this will necessitate a change in the template as well.

**Comment by axelson** [comment]
That makes sense. Thanks.

For reference new PR is #57

**Pull request closed without merging**
