### PR TITLE
Add new spacer component 

### PR DESCRIPTION
**Pull request by acezard**
Suggesting a component used for accurate vertical spacing.

It would be used that way :  `<spacer size="10"></spacer>` and generates a battle-tested 
`<table class="spacer"><tbody><tr><td height="10px" style="font-size:10px;mso-line-height-rule: exactly;line-height:10px;">&nbsp;</td></tr></tbody></table>`

I feel this kind of component can be helpful in the framework because it allows an easy way of managing padding/margins without ever using them (usually unreliable on outlook). For instance it's very nice to make separations between blocks (even with different background colors), or even between elements in a single column.

I will make a pr to the foundation for emails repo because a css rule is also needed (100% width)

### CODE REVIEW

**Comment by gakimball** [comment]
If there's CSS that needs to be added to Foundation for Emails, then can we add *all* the CSS you've got in the `style` attribute? That way we keep Inky's HTML output cleaner.

**Comment by acezard** [comment]
It's possible. The only issue is that the user chose himself the height of the spacer element with the size attribute directly in the element attribute. Instead, I think it would be possible to create defaut css classes like "space-md", "space-lg", or allow the user to create custom classes if he knows what properties to target.

**Comment by gakimball** [comment]
@acezard Oh, I'm sorry, I was totally blind to that :) Makes total sense.

Need to do a bit more internal review with the team and then we can bring this in. Thanks again!

**Comment by rafibomb** [comment]
We like the way you have it @acezard ! I'll be testing it this week to bring it in. Thanks!

**Comment by gakimball** [comment]
@acezard Can you put together a unit test for this new component? We'll need that before we can merge. It would go under [`test/components.js`](https://github.com/zurb/inky/blob/master/test/components.js).

**Comment by acezard** [comment]
I added an unit test and also removed unnecessary css (I put it directly into the css instead. Not sure if that rule is really necessary though but it was suggested to me on the initial issue https://github.com/zurb/foundation-emails/issues/289). Seems

**Comment by gakimball** [comment]
Awesome, thank you!

**Comment by rafibomb** [comment]
@acezard Shoot us an email with your address for some Yeti stickers! foundation at zurb .com

**Comment by rafibomb** [comment]
@acezard Just wanted to make sure I didn't miss your email, did you have a chance to send it?

**Comment by acezard** [comment]
@rafibomb oh, yea I did send it about the time you posted the previous message ! maybe I made a mistake ? my email adress is my github username @gmail.com

**Pull request merged**
