### PR TITLE
Add target="" support for button component

### PR DESCRIPTION
**Pull request by vincentducorps**

### CODE REVIEW

**Comment by rafibomb** [comment]
We have no issue adding this, other than added complexity.

Is there a reason we need it in an email though? And as far as I can tell, most webmail clients automatically open links in new tabs without there being a need for a specified target.

**Comment by vincentducorps** [comment]
This is particularly convenient for the web version of the email. :)

**Comment by gakimball** [comment]
Eventually the parser should copy all (non-custom) attributes from the original tag to the new one, for all components.

**Comment by rafibomb** [comment]
@vincentducorps I think we'll pull this in, but do you think all buttons should automatically have a target="_blank"? Perhaps we can extend Inky to add that?

**Comment by rafibomb** [comment]
Also -  Just published the [Foundation for Emails 2.1](http://zurb.com/article/1434/foundation-for-emails-2-1-supercharge-you) release blog post and the release went out this morning! We also started a discussion on the future of Inky and what amazing integrations can be made. I'm sure you have some comments, questions, or ideas: http://foundation.zurb.com/forum/posts/39717-architecting-the-future-of-foundation-for-emails

**Comment by vincentducorps** [comment]
I don't know, it depends on your specifications.
I believe that we must allow the possibility to specify.

Maybe "_blank" by default and the possibility to make it in "_self".
Otherwise, the proposal @gakimball is not a bad idea.

**Comment by rafibomb** [comment]
Sorry that this might have gotten crossed up with some of the other PR's

I saw that https://github.com/zurb/inky/pull/42 was merged and does the same thing and this one covers all attribute use cases: https://github.com/zurb/inky/pull/45

Do you see anything missing on those that should be addressed?

**Pull request closed without merging**
