### PR TITLE
[update] add original attributes to outputted html

### PR DESCRIPTION
**Pull request by brandonbarringer**
Grabs all the attributes on an inky element, minus 'class', 'id', and 'href', and adds those attributes to the outputted html

### CODE REVIEW

**Comment by rafibomb** [comment]
This is a great PR! I was wonder if there is a good way to pass in valign attributes to tables. This may solve it.

Have to see why the build is failing before merging.

**Comment by brandonbarringer** [comment]
Checks 8&9 where already failed when I forked the repo. 1-7 are stumping me as to why they are failing. The code seems to be working fine on my end.

**Comment by brandonbarringer** [comment]
@rafibomb fixed failed test by leveraging code from issue #37. Also missed a `var` in my for in loop that was failing the rest of the tests. Should be good to go now

**Comment by rafibomb** [comment]
Sweet! Looking to get #37 across the line as well as this killer PR for 6.2.2!

**Comment by rafibomb** [comment]
@brandonbarringer Testing this out today - looks like the attributes are being passed in on the row but not the columns. It would be ideal to be able to pass in attributes onto the columns as well. 

Things like:
- valign
- dir
- align

Are you able to add that to this feature?

**Comment by rafibomb** [comment]
Made a small change to the function to allow multiple attributes as well as a test for columns. Hope that helps you add the columns attributes. Let me know if questions come up!

**Comment by brandonbarringer** [comment]
Sure. I will get something pushed up soon.

**Comment by brandonbarringer** [comment]
Alright. I was able to add the same functionality to the columns by creating a utility function. Let me know if you have any issues with the way this was implemented. I had to change the structure a bit to get it to work across modules.

**Comment by rafibomb** [comment]
Amazing PR! This is great because we tested out vertical alignment and source ordering with this and it works great! https://github.com/zurb/foundation-emails/commit/d9353f044793c0e9167295dff3e37f93c8e8b350

2.2 is looking like it's feature rich thanks to your help!

**Comment by brandonbarringer** [comment]
Glad I could help. Really love this framework and plan on contributing as much I can as I continue using it.

**Comment by kareljan** [comment]
Is it possible to copy stuff like title to the element? 

```
<menu>
  <item href="link" title="E-shop" target="_blank">E-shop</item>
</menu>
```
gives me with the latest version

```
<table align="center" class="menu float-center"><tr><td><table><tr>
  <th title="E-shop" target="_blank" class="menu-item float-center"><a href="link">E-shop</a></th>
</tr></table></td></tr></table>
```

You would expect the title and target attribute on the a-tag rather than on the th-tag.
And the same with buttons. When I add a target and title attribute to a button, the a-tag it compiles to gets the target (this is good), but the title attribute disappears.

How can we fix this?

Thanks

**Pull request merged**
